import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import BottomNavigation from '@/components/BottomNavigation';
import SideNav from '@/components/Sidenav';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Meetings',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            closeOnClick
            pauseOnHover
            theme="colored"
          />
          <SideNav />
          <main className="mx-auto">{children}</main>
          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
