import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav, { SidebarItem } from "@/components/Sidenav";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meetings",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
            <ToastContainer
               position="top-right"
               autoClose={2000}
               hideProgressBar={false}
               closeOnClick
               pauseOnHover
               theme="colored"
            />
            <SideNav/>
            <main className="mx-auto">
                {children}
            </main>
        </div>
      </body>
    </html>
  );
}
