name: Deploy Nextjs App to EC2

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deployment script
        run: |
          scp -o StrictHostKeyChecking=no deploy.sh ubuntu@{{ secrets.EC2_HOST }}:/home/ubuntu/deploy.sh
          ssh -o StrictHostKeyChecking=no ubuntu@{{ secrets.EC2_HOST }} 'chmod +x /home/ubuntu/deploy.sh && /home/ubuntu/deploy.sh'


